return {
  kind = {
    Class = "󰌗",
    Color = "󰏘",
    Constant = "󰇽",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = "",
    Keyword = "󰌋",
    Method = "m",
    Module = "",
    Operator = "󰆕",
    Property = "",
    Reference = "",
    Snippet = "",
    Struct = "",
    Text = "󰉿",
    TypeParameter = "󰊄",
    Unit = "",
    Value = "󰎠",
    Variable = "󰆧",
  },
  diagnostic = {
    BoldError = "",
    BoldHint = "",
    BoldInformation = "",
    BoldQuestion = "",
    BoldWarning = "",
    Debug = "",
    Error = "",
    Hint = "󰌶",
    Information = "",
    Question = "",
    Trace = "󰙏",
    Warning = "",
  },
  package = {
    Installed = "",
    Pending = "",
    Uninstalled = "",
  },
}
